### ISSUE TITLE
IndexError: index 50 is out of bounds for dimension 0 with size 50

### ISSUE THREAD

**Issue by flydragon2018** [tiwarikajal/Seq2SQL-#5]
(7000 2%) 3.1731
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    baseline.run_baseline()
  File "/home/zzl/nlp/seq2sql_nlp/baseline/baseline.py", line 175, in run_baseline
    lr_best = hyperparam(hidden_size)
  File "/home/zzl/nlp/seq2sql_nlp/baseline/baseline.py", line 82, in hyperparam
    trainIters(encoder1, attn_decoder1, 250000, print_every=1000, plot_every=1000,learning_rate=l) #Change number of iter
  File "/home/zzl/nlp/seq2sql_nlp/baseline/baseline.py", line 105, in trainIters
    decoder, encoder_optimizer, decoder_optimizer, criterion)
  File "/home/zzl/nlp/seq2sql_nlp/baseline/baseline.py", line 34, in train
    encoder_outputs[ei] = encoder_output[0, 0]
IndexError: index 50 is out of bounds for dimension 0 with size 50

**Comment by flydragon2018** [comment]
(14000 5%) 2.8525
(15000 6%) 2.8401
(16000 6%) 2.7109
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    baseline.run_baseline()
  File "/home/zzl/nlp/seq2sql_nlp/baseline/baseline.py", line 175, in run_baseline
    lr_best = hyperparam(hidden_size)
  File "/home/zzl/nlp/seq2sql_nlp/baseline/baseline.py", line 82, in hyperparam
    trainIters(encoder1, attn_decoder1, 250000, print_every=1000, plot_every=1000,learning_rate=l) #Change number of iter
  File "/home/zzl/nlp/seq2sql_nlp/baseline/baseline.py", line 105, in trainIters
    decoder, encoder_optimizer, decoder_optimizer, criterion)
  File "/home/zzl/nlp/seq2sql_nlp/baseline/baseline.py", line 34, in train
    encoder_outputs[ei] = encoder_output[0, 0]
IndexError: index 50 is out of bounds for dimension 0 with size 50

****************************************************************************************

different running, different stop time, but same error.

**Comment by BellangerSebastien** [comment]
hi have the same problem 

Do you solve it ? 

Edit : i print in a for loop the value of "ei" i think when ei=50 the program crash 
i add : if ei < 50:

In baseline.py

    for ei in range(input_length):
        if ei < 50:
            encoder_output, encoder_hidden = encoder(
                input_tensor[ei], encoder_hidden)

            encoder_outputs[ei] = encoder_output[0, 0]

im totaly noob on MachineLearning so i dont know if is good to filter less than 50 or it's a miss on the source code

**Comment by tiwarikajal** [comment]
In /util/constants.py , we have a constant MAX_LENGTH set to 50 along with other hyperparameters that users have to change as per their need.
Setting MAX_LENGTH to more than 200 or something should solve your problem here.
